services:
  - type: web
    name: yischool-web
    env: 
      - type: python
        PYTHON_VERSION: 3.11.9
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: yischool-super-secret-key